// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    Delete: typeof import('./src/components/Delete.vue')['default']
    Exit: typeof import('./src/components/Exit.vue')['default']
    Minimum: typeof import('./src/components/Minimum.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NProgress: typeof import('naive-ui')['NProgress']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTooltip: typeof import('naive-ui')['NTooltip']
    OtherFunction: typeof import('./src/components/OtherFunction.vue')['default']
    Pushpin: typeof import('./src/components/Pushpin.vue')['default']
    Question: typeof import('./src/components/Question.vue')['default']
    Reset: typeof import('./src/components/Reset.vue')['default']
    Setting: typeof import('./src/components/Setting.vue')['default']
    Start: typeof import('./src/components/Start.vue')['default']
  }
}
